### ISSUE TITLE
Initial blank lines in code are ignored

### ISSUE THREAD

**Issue by samuelmaddock** [cartman300/gluac#5]
If the input given to `gluac` contains any blank lines at the beginning of the code, they are ignored. This affects the reported line number when an error is detected in the code. Here's an example:

![code](http://samuelmaddock.com/up/2015-01-01_15-45-15.png)

The actual syntax error occurs on line 13 while `gluac` is reporting line 10.

**Comment by cartman300** [comment]
Ah sorry, i'm trimming input for some reason, a moment please

**Comment by cartman300** [comment]
Fixed

**Comment by samuelmaddock** [comment]
Thanks for the fast response. :+1:
