### ISSUE TITLE
Seeking help in regards to this not working right

### ISSUE THREAD

**Issue by VaasKahnGrim** [cartman300/gluac#6]
While I know its a 5y old repo I'm still trying to figure out how to use it. the only other alternetive I know of is by a guy who is nolonger active on github anymore it seems.

Currently I have the tier0.dll and the lua_shared.dll both in the same folder as gluac.exe the compile worked succesfully and it seems to run, however it seems to believe that the lua_shared.dll does not exist.

Below is the error its giving me when trying to run it.

`C:\Users\USERFOLDER\Downloads\gluac-master (2)\gluac-master\gluac\obj\Debug>gluac.exe -p test.lua
System.DllNotFoundException: Unable to load DLL 'lua_shared.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at GSharp.Lua.NewState()
   at gluac.Program.Run(String In, String Out, String ChunkName) in C:\Users\USERFOLDER\Downloads\gluac-master (2)\gluac-master\gluac\Program.cs:line 132
   at gluac.Program.SafeMain(String[] Args) in C:\Users\USERFOLDER\Downloads\gluac-master (2)\gluac-master\gluac\Program.cs:line 127
   at gluac.Program.Main(String[] Args) in C:\Users\USERFOLDER\Downloads\gluac-master (2)\gluac-master\gluac\Program.cs:line 101`

aswell here is the contents of the test.lua file in hopes that it helps

`print'testing strings print'
local table_of_stuff = {'cactus',1234}
for k,v in pairs(table_of_stuff)do
    print(v)
end
print'GLUAC Compiled it properly!!!'`

**Comment by sbarisic** [comment]
I'll look into it, you can expect an update or fix within an hour

**Comment by VaasKahnGrim** [comment]
thank you so much dude, I really appreciate this :)

**Comment by sbarisic** [comment]
It seems lua_shared got an additional dependency for vstdlib.dll, copy it from GarrysMod/bin/ and it should work

**Comment by VaasKahnGrim** [comment]
it worked! thanks man :)
